# Change these first
owner: pgedeon # Your GitHub organization or username, where this repository lives
repo: hyag # The name of this repository

sites:
  - name: HYAG
    url: https://www.hanseyachtsag.com
  - name: HYAG Shop
    url: https://shop.hanseyachtsag.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.hanseyachtsag.com
  baseUrl: /us
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hanse
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "**real-time** data from GitHub repository."
  navbar:
    - title: Status
      href: /
    - title: Hanse
      href: https://www.hanseyachtsag.com/hanse/us

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
