# Change these first
owner: pgedeon # Your GitHub organization or username, where this repository lives
repo: hyag # The name of this repository

sites:
  - name: HYAG
    url: https://www.hanseyachtsag.com/us/
  - name: HYAG Shop
    url: https://shop.hanseyachtsag.com/
  - name: Hanse Yachts
    url: https://www.hanseyachtsag.com/hanse/us/
    icon: https://www.hanseyachtsag.com/hanse/assets/img/favicon.ico
  - name: Moody Boats
    url: https://www.hanseyachtsag.com/moody/us/
    icon: https://www.hanseyachtsag.com/moody/assets/img/favicon.ico 
  - name: Dehler Yachts
    url: https://www.hanseyachtsag.com/dehler/us/
    icon: https://www.hanseyachtsag.com/dehler/typo3conf/ext/hanse_site/Resources/Public/img/favicon-dehler-gray-trans.ico
  - name: FJORD Boats
    url: https://www.hanseyachtsag.com/fjord/us/
    icon: https://www.hanseyachtsag.com/fjord/typo3conf/ext/hanse_site/Resources/Public/dist/shared/media/favicons/fjord.ico
  - name: SEALINE
    url: https://www.hanseyachtsag.com/sealine/us/
    icon: https://www.hanseyachtsag.com/sealine/typo3conf/ext/hanse_site/Resources/Public/dist/shared/media/favicons/sealine.ico
  - name: RYCK
    url: https://www.hanseyachtsag.com/ryck/us/
    icon: https://www.hanseyachtsag.com/ryck/media/favicon_c.png
  - name: HYAG Ping
    check: "tcp-ping"
    url: 212.237.244.91
    port: 80
  - name: AG Sailboats
    url: https://www.hanseyachtsag.com/us/sailboats/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/catamarans/
	- name: AG Motorboats
    url: https://www.hanseyachtsag.com/us/motorboats/
	- name: AG Yachts
    url: https://www.hanseyachtsag.com/us/yachts/
	- name: AG Brands
    url: https://www.hanseyachtsag.com/us/brands/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/hanse/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/dehler/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/moody/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/privilege/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/fjord/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/sealine/
	- name: AG Catamarans
    url: https://www.hanseyachtsag.com/us/brands/ryck/
  - name: Fraser Yachts
    url: https://www.fraseryachts.com/
  - name: Beneteau    
    url: https://www.beneteau.com/us

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.hanseyachtsag.com
  baseUrl: /us
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hanse
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "**real-time** data from GitHub repository."
  navbar:
    - title: Status
      href: /
    - title: Hanse
      href: https://www.hanseyachtsag.com/hanse/us

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
